include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: false
    prefer_const_declarations: false
    prefer_final_locals: false
    prefer_final_fields: false
    avoid_print: false
